name: Keep Workflow Alive

on:
  schedule:
    - cron: '0 5 1 * *'
  workflow_dispatch: # manual job trigger on request

jobs:
  keep_alive_job:
    runs-on: ubuntu-22.04
    steps:
      - name: clone the repository
        uses: actions/checkout@v5
        with:
          ref: br_dummy

      - name: push to dummy branch to keep workflow alive
        run: |
          echo -e "\e[1m[L] Keeping the workflow alive by pushing to dummy branch\e[0m"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo "Workflow kept alive at $(date)" > keep_alive.txt
          git pull
          git add keep_alive.txt
          git commit -m "Keep workflow alive at $(date)"
          git push --set-upstream origin br_dummy

#
# end of file
#
